version: "3.1"

services:
  metaboss:
    build: ./
    container_name: metaboss
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./main.sh:/app/main.sh
      - ./keypair.json:/keypair.json
